### PR TITLE
set up react using parcel

### LINKED ISSUE #4: [FEATURE] Setup the Project using Parcel
What we have right now is a JS template.  This issue will include:
 - Setting up the react project using parcel.
 * Some good material to help with this task is '[setting up with parcel'](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-react-project-with-parcel)

### PR DESCRIPTION
**Pull request by Danielshow**
## Description
Set up react project using parcel
#4

### CODE REVIEW

**Review by katungi — APPROVED** [review]

**Review by katungi — APPROVED** [review]
LGTM!!

**Review by wathigo — APPROVED** [review]
### Approved :heavy_check_mark:

**Comment by Danielshow** [comment]
I can't merge, set the number of approval to 2 so I'd be able to merge

**Review by katungi — COMMENTED** [review]
@Danielshow I have set it to 2 reviews.

**Comment by Danielshow** [comment]
Codacy is still running, can't merge until it finishes running., Can you give me admin access
@katungi

**Review by katungi — COMMENTED** [review]
I have set you as an admin. @Danielshow

**Pull request merged**
